---
abstract: 'BeLike::KENTNL when you build your distributions.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Dist::Zilla::Plugin::Author::KENTNL::TravisCI: '0.001002'
  Dist::Zilla::Plugin::Git::NextVersion::Sanitized: '0'
  Dist::Zilla::Plugin::ModuleBuild: '0'
  Dist::Zilla::Plugin::Prereqs::MatchInstalled: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::pushd: '0'
  FindBin: '0'
  Git::Wrapper: '0'
  Module::Build: '0'
  Module::Metadata: '0'
  Path::Class::Dir: '0'
  Path::Tiny: '0'
  Test::DZil: '0'
  Test::Fatal: '0'
  Test::File::ShareDir: v0.3.0
  Test::More: '0.89'
  Test::Output: '0'
  lib: '0'
  perl: '5.008'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.10'
  perl: '5.008'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-Author-KENTNL
provides:
  Dist::Zilla::MintingProfile::Author::KENTNL:
    file: lib/Dist/Zilla/MintingProfile/Author/KENTNL.pm
    version: '2.025001'
  Dist::Zilla::Plugin::Author::KENTNL::DistINI:
    file: lib/Dist/Zilla/Plugin/Author/KENTNL/DistINI.pm
    version: '2.025001'
  Dist::Zilla::Plugin::Author::KENTNL::MinimumPerl:
    file: lib/Dist/Zilla/Plugin/Author/KENTNL/MinimumPerl.pm
    version: '2.025001'
  Dist::Zilla::PluginBundle::Author::KENTNL:
    file: lib/Dist/Zilla/PluginBundle/Author/KENTNL.pm
    version: '2.025001'
recommends:
  CHI: '0'
  CHI::Driver::LMDB: '0'
  CPAN::Changes::Dependencies::Details: '0.001000'
  CPAN::Changes::Group::Dependencies::Stats: '0.002002'
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs::Diff: '0'
  Cpanel::JSON::XS: '0'
  Data::Serializer::Sereal: '0'
  Dist::Zilla::Plugin::Author::KENTNL::TravisCI: '0.001001'
  Dist::Zilla::Plugin::Bootstrap::lib: '0.04000002'
  Dist::Zilla::Plugin::Git::NextVersion::Sanitized: '0'
  Dist::Zilla::Plugin::MakeMaker: '0'
  Dist::Zilla::Plugin::ModuleBuild: '0'
  Dist::Zilla::Plugin::ModuleBuildTiny: '0'
  Dist::Zilla::Plugin::PerlTidy: '0.14'
  Dist::Zilla::Plugin::Prereqs::MatchInstalled: '0'
  Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled: '0'
  Dist::Zilla::Util::EmulatePhase: '0.01025803'
  IO::Socket::SSL: '1.962'
  JSON::MaybeXS: '0'
  LMDB_File: '0'
  LWP::Protocol::https: '6.04'
  Moo: '1.000008'
  Moose: '2.1201'
  MooseX::Has::Sugar: '1.000000'
  MooseX::Types: '0.41'
  Net::GitHub: '0'
  Net::SSLeay: '1.57'
  Perl::Critic::Bangs: '0'
  Perl::Critic::Compatibility: '0'
  Perl::Critic::Deprecated: '0'
  Perl::Critic::Itch: '0'
  Perl::Critic::Lax: '0'
  Perl::Critic::More: '0'
  Perl::Critic::Policy::Variables::ProhibitUnusedVarsStricter: '0'
  Perl::Critic::Pulp: '0'
  Perl::Critic::StricterSubs: '0'
  Perl::Critic::Swift: '0'
  Perl::Critic::Tics: '0'
  Perl::PrereqScanner: '1.019'
  Pod::Coverage::TrustPod: '0.100003'
  Pod::Elemental::PerlMunger: '0.200001'
  Test::CPAN::Meta: '0.23'
  Test::EOL: '1.5'
  Test::Perl::Critic: '1.02'
  Test::Pod: '1.48'
  Test::Pod::Coverage: '1.08'
  namespace::autoclean: '0.15'
requires:
  Carp: '0'
  Dist::Zilla: '5.011'
  Dist::Zilla::File::FromCode: '0'
  Dist::Zilla::Plugin::Author::KENTNL::CONTRIBUTING: '0.001002'
  Dist::Zilla::Plugin::Author::KENTNL::RecommendFixes: '0.004002'
  Dist::Zilla::Plugin::Author::KENTNL::TravisCI: '0.001002'
  Dist::Zilla::Plugin::Authority: '1.006'
  Dist::Zilla::Plugin::AutoPrereqs: '0'
  Dist::Zilla::Plugin::BumpVersionAfterRelease: '0'
  Dist::Zilla::Plugin::ConfirmRelease: '0'
  Dist::Zilla::Plugin::CopyFilesFromBuild: '0'
  Dist::Zilla::Plugin::Git::Check: '0'
  Dist::Zilla::Plugin::Git::Commit: '0'
  Dist::Zilla::Plugin::Git::CommitBuild: '0'
  Dist::Zilla::Plugin::Git::Contributors: '0.006'
  Dist::Zilla::Plugin::Git::GatherDir: '0'
  Dist::Zilla::Plugin::Git::NextRelease: '0.004000'
  Dist::Zilla::Plugin::Git::Tag: '0'
  Dist::Zilla::Plugin::GithubMeta: '0'
  Dist::Zilla::Plugin::License: '0'
  Dist::Zilla::Plugin::MakeMaker: '0'
  Dist::Zilla::Plugin::Manifest: '0'
  Dist::Zilla::Plugin::ManifestSkip: '0'
  Dist::Zilla::Plugin::MetaConfig: '0'
  Dist::Zilla::Plugin::MetaData::BuiltWith: '1.004000'
  Dist::Zilla::Plugin::MetaJSON: '0'
  Dist::Zilla::Plugin::MetaProvides::Package: '1.14000001'
  Dist::Zilla::Plugin::MetaTests: '0'
  Dist::Zilla::Plugin::MetaYAML::Minimal: '0'
  Dist::Zilla::Plugin::MinimumPerl: '0'
  Dist::Zilla::Plugin::PodCoverageTests: '0'
  Dist::Zilla::Plugin::PodSyntaxTests: '0'
  Dist::Zilla::Plugin::PodWeaver: '0'
  Dist::Zilla::Plugin::Prereqs: '0'
  Dist::Zilla::Plugin::Prereqs::AuthorDeps: '0'
  Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled: '0'
  Dist::Zilla::Plugin::Prereqs::Upgrade: '0'
  Dist::Zilla::Plugin::Readme::Brief: '0'
  Dist::Zilla::Plugin::ReadmeAnyFromPod: '0'
  Dist::Zilla::Plugin::RemovePrereqs::Provided: '0'
  Dist::Zilla::Plugin::RewriteVersion::Sanitized: '0'
  Dist::Zilla::Plugin::RunExtraTests: '0'
  Dist::Zilla::Plugin::Test::CPAN::Changes: '0'
  Dist::Zilla::Plugin::Test::Compile::PerFile: '0'
  Dist::Zilla::Plugin::Test::EOL: '0'
  Dist::Zilla::Plugin::Test::Kwalitee: '0'
  Dist::Zilla::Plugin::Test::MinimumVersion: '0'
  Dist::Zilla::Plugin::Test::Perl::Critic: '0'
  Dist::Zilla::Plugin::Test::ReportPrereqs: '0'
  Dist::Zilla::Plugin::TestRelease: '0'
  Dist::Zilla::Plugin::Twitter: '0'
  Dist::Zilla::Plugin::UploadToCPAN: '0'
  Dist::Zilla::Role::BundleDeps: '0'
  Dist::Zilla::Role::FileGatherer: '0'
  Dist::Zilla::Role::MintingProfile::ShareDir: '0'
  Dist::Zilla::Role::PluginBundle: '0'
  Dist::Zilla::Role::PluginBundle::Config::Slicer: '0'
  Dist::Zilla::Role::PluginBundle::PluginRemover: '0'
  Dist::Zilla::Util::ConfigDumper: '0'
  Dist::Zilla::Util::CurrentCmd: '0'
  Moo: '0'
  Moose: '0'
  Moose::Util::TypeConstraints: '0'
  String::Formatter: '0'
  namespace::autoclean: '0'
  perl: '5.008'
  strict: '0'
  utf8: '0'
  version: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-PluginBundle-Author-KENTNL/issues
  homepage: https://github.com/kentnl/Dist-Zilla-PluginBundle-Author-KENTNL
  repository: https://github.com/kentnl/Dist-Zilla-PluginBundle-Author-KENTNL.git
version: '2.025001'
