---
abstract: 'BeLike::KENTNL when you build your distributions.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  FindBin: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-KENTNL
provides:
  Dist::Zilla::Plugin::Author::KENTNL::DistINI:
    file: lib/Dist/Zilla/Plugin/Author/KENTNL/DistINI.pm
    version: 0.01007922
  Dist::Zilla::PluginBundle::KENTNL:
    file: lib/Dist/Zilla/PluginBundle/KENTNL.pm
    version: 0.01007922
requires:
  Carp: 0
  Dist::Zilla: 4.101612
  Dist::Zilla::File::FromCode: 0
  Dist::Zilla::Plugin::AutoPrereq: 0
  Dist::Zilla::Plugin::AutoVersion::Relative: 0.01034313
  Dist::Zilla::Plugin::CompileTests: 1.101800
  Dist::Zilla::Plugin::ConfirmRelease: 0
  Dist::Zilla::Plugin::EOLTests: 0.02
  Dist::Zilla::Plugin::ExtraTests: 0
  Dist::Zilla::Plugin::FakeRelease: 0
  Dist::Zilla::Plugin::GatherDir: 0
  Dist::Zilla::Plugin::Git::Check: 1.102040
  Dist::Zilla::Plugin::Git::CommitBuild: 1.102040
  Dist::Zilla::Plugin::Git::Tag: 1.102040
  Dist::Zilla::Plugin::GithubMeta: 0.08
  Dist::Zilla::Plugin::KwaliteeTests: 1.101420
  Dist::Zilla::Plugin::License: 0
  Dist::Zilla::Plugin::Manifest: 0
  Dist::Zilla::Plugin::ManifestSkip: 0
  Dist::Zilla::Plugin::MetaConfig: 0
  Dist::Zilla::Plugin::MetaData::BuiltWith: 0.01005122
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaProvides: 1.11034201
  Dist::Zilla::Plugin::MetaProvides::Package: 1.11034304
  Dist::Zilla::Plugin::MetaTests: 0
  Dist::Zilla::Plugin::MetaYAML: 0
  Dist::Zilla::Plugin::ModuleBuild: 0
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 3.093321
  Dist::Zilla::Plugin::PortabilityTests: 1.101420
  Dist::Zilla::Plugin::PruneCruft: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0.12
  Dist::Zilla::Plugin::ReportVersions::Tiny: 1.01
  Dist::Zilla::Plugin::TestRelease: 0
  Dist::Zilla::Plugin::Twitter: 0.007
  Dist::Zilla::Plugin::UploadToCPAN: 0
  Dist::Zilla::Role::FileGatherer: 0
  Dist::Zilla::Role::PluginBundle: 0
  IO::Socket::SSL: 0
  Moose: 1.01
  Moose::Autobox: 0
  MooseX::Has::Sugar: 0.05044
  MooseX::Types: 0.21
  Net::SSLeay: 1.36
  Pod::Coverage::TrustPod: 0
  String::Formatter: 0
  Test::CPAN::Meta: 0
  Test::EOL: 0.9
  namespace::autoclean: 0.09
resources:
  homepage: http://github.com/kentfredric/dist-zilla-pluginbundle-kentnl/tree
  repository: git://github.com/kentfredric/dist-zilla-pluginbundle-kentnl.git
version: 0.01007922
x_BuiltWith:
  modules:
    Carp: 1.16
    Dist::Zilla: 4.101900
    Dist::Zilla::File::FromCode: 4.101900
    Dist::Zilla::Plugin::AutoPrereq: 4.101900
    Dist::Zilla::Plugin::AutoVersion::Relative: 0.01034313
    Dist::Zilla::Plugin::CompileTests: 1.101800
    Dist::Zilla::Plugin::ConfirmRelease: 4.101900
    Dist::Zilla::Plugin::EOLTests: 0.02
    Dist::Zilla::Plugin::ExtraTests: 4.101900
    Dist::Zilla::Plugin::FakeRelease: 4.101900
    Dist::Zilla::Plugin::GatherDir: 4.101900
    Dist::Zilla::Plugin::Git::Check: 1.102040
    Dist::Zilla::Plugin::Git::CommitBuild: 1.102040
    Dist::Zilla::Plugin::Git::Tag: 1.102040
    Dist::Zilla::Plugin::GithubMeta: 0.10
    Dist::Zilla::Plugin::KwaliteeTests: 1.101420
    Dist::Zilla::Plugin::License: 4.101900
    Dist::Zilla::Plugin::Manifest: 4.101900
    Dist::Zilla::Plugin::ManifestSkip: 4.101900
    Dist::Zilla::Plugin::MetaConfig: 4.101900
    Dist::Zilla::Plugin::MetaData::BuiltWith: 0.01005122
    Dist::Zilla::Plugin::MetaJSON: 4.101900
    Dist::Zilla::Plugin::MetaProvides: 1.11034201
    Dist::Zilla::Plugin::MetaProvides::Package: 1.11034304
    Dist::Zilla::Plugin::MetaTests: 4.101900
    Dist::Zilla::Plugin::MetaYAML: 4.101900
    Dist::Zilla::Plugin::ModuleBuild: 4.101900
    Dist::Zilla::Plugin::PkgVersion: 4.101900
    Dist::Zilla::Plugin::PodCoverageTests: 4.101900
    Dist::Zilla::Plugin::PodSyntaxTests: 4.101900
    Dist::Zilla::Plugin::PodWeaver: 3.101640
    Dist::Zilla::Plugin::PortabilityTests: 1.101420
    Dist::Zilla::Plugin::PruneCruft: 4.101900
    Dist::Zilla::Plugin::ReadmeFromPod: 0.12
    Dist::Zilla::Plugin::ReportVersions::Tiny: 1.01
    Dist::Zilla::Plugin::TestRelease: 4.101900
    Dist::Zilla::Plugin::Twitter: 0.008
    Dist::Zilla::Plugin::UploadToCPAN: 4.101900
    Dist::Zilla::Role::FileGatherer: 4.101900
    Dist::Zilla::Role::PluginBundle: 4.101900
    File::Find: 1.15
    File::Spec: 3.31
    File::Temp: 0.22
    FindBin: 1.50
    IO::Socket::SSL: 1.33
    Module::Build: 0.3607
    Moose: 1.08
    Moose::Autobox: 0.11
    MooseX::Has::Sugar: 0.05044303
    MooseX::Types: 0.22
    Net::SSLeay: 1.36
    Pod::Coverage::TrustPod: 0.092830
    String::Formatter: 0.100720
    Test::CPAN::Meta: 0.17
    Test::EOL: 0.9
    Test::More: 0.94
    namespace::autoclean: 0.11
  perl: 5.012001
  platform: linux
  uname: "Linux 2.6.34-gentoo x86_64 GenuineIntel GNU/Linux\n"
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::AutoVersion::Relative
      name: '@KENTNL/AutoVersion::Relative'
      version: 0.01034313
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@KENTNL/GatherDir'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@KENTNL/MetaConfig'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@KENTNL/PruneCruft'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@KENTNL/GithubMeta'
      version: 0.10
    -
      class: Dist::Zilla::Plugin::License
      name: '@KENTNL/License'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@KENTNL/PkgVersion'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@KENTNL/PodWeaver'
      version: 3.101640
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@KENTNL/MetaProvides::Package'
      version: 1.11034304
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@KENTNL/MetaJSON'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@KENTNL/MetaYAML'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@KENTNL/ModuleBuild'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@KENTNL/ReadmeFromPod'
      version: 0.12
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@KENTNL/ManifestSkip'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@KENTNL/Manifest'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@KENTNL/AutoPrereq'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_uname: 1
          uname:
            uname_args:
              - '-s'
              - '-o'
              - '-r'
              - '-m'
              - '-i'
            uname_call: uname
      name: '@KENTNL/MetaData::BuiltWith'
      version: 0.01005122
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@KENTNL/CompileTests'
      version: 1.101800
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@KENTNL/MetaTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@KENTNL/PodCoverageTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@KENTNL/PodSyntaxTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@KENTNL/ReportVersions::Tiny'
      version: 1.01
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@KENTNL/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@KENTNL/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@KENTNL/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@KENTNL/ExtraTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@KENTNL/TestRelease'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@KENTNL/ConfirmRelease'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@KENTNL/Git::Check'
      version: 1.102040
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@KENTNL/NextRelease'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@KENTNL/Git::Tag/tag_master'
      version: 1.102040
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@KENTNL/Git::Commit'
      version: 1.102040
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@KENTNL/Git::CommitBuild'
      version: 1.102040
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@KENTNL/Git::Tag/tag_release'
      version: 1.102040
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@KENTNL/UploadToCPAN'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@KENTNL/Twitter'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Prereq
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereq
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.101900
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.101900
