---
abstract: 'BeLike::KENTNL when you build your distributions.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Capture::Tiny: 0
  File::Find: 0
  File::Temp: 0
  File::pushd: 0
  FindBin: 0
  Git::Wrapper: 0
  JSON: 0
  Module::Build: 0.3601
  Path::Class: 0
  Test::DZil: 0
  Test::Fatal: 0
  Test::File::ShareDir: v0.3.0
  Test::More: 0.88
  Test::Output: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-KENTNL
provides:
  Dist::Zilla::MintingProfile::Author::KENTNL:
    file: lib/Dist/Zilla/MintingProfile/Author/KENTNL.pm
    version: v1.4.1
  Dist::Zilla::Plugin::Author::KENTNL::DistINI:
    file: lib/Dist/Zilla/Plugin/Author/KENTNL/DistINI.pm
    version: v1.4.1
  Dist::Zilla::Plugin::Author::KENTNL::MinimumPerl:
    file: lib/Dist/Zilla/Plugin/Author/KENTNL/MinimumPerl.pm
    version: v1.4.1
  Dist::Zilla::PluginBundle::Author::KENTNL:
    file: lib/Dist/Zilla/PluginBundle/Author/KENTNL.pm
    version: v1.4.1
requires:
  Carp: 0
  Class::Load: 0
  Dist::Zilla: 4.300000
  Dist::Zilla::File::FromCode: 0
  Dist::Zilla::Plugin::Authority: 0
  Dist::Zilla::Plugin::AutoPrereqs: 4.200011
  Dist::Zilla::Plugin::CheckExtraTests: 0
  Dist::Zilla::Plugin::ConfirmRelease: 0
  Dist::Zilla::Plugin::EOLTests: 0.02
  Dist::Zilla::Plugin::FakeRelease: 0
  Dist::Zilla::Plugin::GatherDir: 0
  Dist::Zilla::Plugin::Git::Check: 1.102040
  Dist::Zilla::Plugin::Git::CommitBuild: 1.102040
  Dist::Zilla::Plugin::Git::GatherDir: 1.120970
  Dist::Zilla::Plugin::Git::NextVersion: 1.102810
  Dist::Zilla::Plugin::Git::Tag: 1.102040
  Dist::Zilla::Plugin::GithubMeta: 0.08
  Dist::Zilla::Plugin::License: 0
  Dist::Zilla::Plugin::Manifest: 0
  Dist::Zilla::Plugin::ManifestSkip: 0
  Dist::Zilla::Plugin::MetaConfig: 0
  Dist::Zilla::Plugin::MetaData::BuiltWith: 0.03000000
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaProvides: 1.14000000
  Dist::Zilla::Plugin::MetaProvides::Package: 1.14000001
  Dist::Zilla::Plugin::MetaTests: 0
  Dist::Zilla::Plugin::MetaYAML: 0
  Dist::Zilla::Plugin::MinimumPerl: 0
  Dist::Zilla::Plugin::ModuleBuild: 0
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 3.093321
  Dist::Zilla::Plugin::Prereqs: 0
  Dist::Zilla::Plugin::PruneCruft: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0.12
  Dist::Zilla::Plugin::ReportVersions::Tiny: 1.01
  Dist::Zilla::Plugin::Test::CPAN::Changes: 0
  Dist::Zilla::Plugin::Test::Compile: 1.112400
  Dist::Zilla::Plugin::Test::Kwalitee: 1.112410
  Dist::Zilla::Plugin::Test::MinimumVersion: 0
  Dist::Zilla::Plugin::Test::Perl::Critic: 1.102280
  Dist::Zilla::Plugin::TestRelease: 0
  Dist::Zilla::Plugin::Twitter: 0.011
  Dist::Zilla::Plugin::UploadToCPAN: 0
  Dist::Zilla::Role::FileGatherer: 0
  Dist::Zilla::Role::MintingProfile::ShareDir: 0
  Dist::Zilla::Role::PluginBundle: 0
  IO::Socket::SSL: 0
  LWP::Protocol::https: 6.00
  Moose: 1.01
  Moose::Autobox: 0
  MooseX::Has::Sugar: 0.05044
  MooseX::Types: 0.21
  Net::SSLeay: 1.36
  Perl::PrereqScanner: 1.006
  Pod::Coverage::TrustPod: 0
  Pod::Weaver::Plugin::Encoding: 0
  String::Formatter: 0
  Test::CPAN::Meta: 0
  Test::EOL: 0.9
  Test::Perl::Critic: 0
  namespace::autoclean: 0.09
  perl: v5.10.0
  strict: 0
  version: 0
  warnings: 0
resources:
  homepage: https://github.com/kentfredric/Dist-Zilla-PluginBundle-Author-KENTNL
  repository: https://github.com/kentfredric/Dist-Zilla-PluginBundle-Author-KENTNL.git
version: 1.4.1
x_BuiltWith:
  modules:
    Capture::Tiny: 0.17
    Carp: 1.25
    Class::Load: 0.19
    Dist::Zilla: 4.300014
    Dist::Zilla::File::FromCode: 4.300014
    Dist::Zilla::Plugin::Authority: 1.006
    Dist::Zilla::Plugin::AutoPrereqs: 4.300014
    Dist::Zilla::Plugin::Bootstrap::lib: 0.01023601
    Dist::Zilla::Plugin::CheckExtraTests: 0.004
    Dist::Zilla::Plugin::ConfirmRelease: 4.300014
    Dist::Zilla::Plugin::EOLTests: 0.02
    Dist::Zilla::Plugin::FakeRelease: 4.300014
    Dist::Zilla::Plugin::GatherDir: 4.300014
    Dist::Zilla::Plugin::Git::Check: 1.121010
    Dist::Zilla::Plugin::Git::CommitBuild: 1.121010
    Dist::Zilla::Plugin::Git::GatherDir: 1.121010
    Dist::Zilla::Plugin::Git::NextVersion: 1.121010
    Dist::Zilla::Plugin::Git::Tag: 1.121010
    Dist::Zilla::Plugin::GithubMeta: 0.28
    Dist::Zilla::Plugin::License: 4.300014
    Dist::Zilla::Plugin::Manifest: 4.300014
    Dist::Zilla::Plugin::ManifestSkip: 4.300014
    Dist::Zilla::Plugin::MetaConfig: 4.300014
    Dist::Zilla::Plugin::MetaData::BuiltWith: 0.03000000
    Dist::Zilla::Plugin::MetaJSON: 4.300014
    Dist::Zilla::Plugin::MetaProvides: 1.14000000
    Dist::Zilla::Plugin::MetaProvides::Package: 1.14000001
    Dist::Zilla::Plugin::MetaTests: 4.300014
    Dist::Zilla::Plugin::MetaYAML: 4.300014
    Dist::Zilla::Plugin::MinimumPerl: 1.003
    Dist::Zilla::Plugin::ModuleBuild: 4.300014
    Dist::Zilla::Plugin::PkgVersion: 4.300014
    Dist::Zilla::Plugin::PodCoverageTests: 4.300014
    Dist::Zilla::Plugin::PodSyntaxTests: 4.300014
    Dist::Zilla::Plugin::PodWeaver: 3.101641
    Dist::Zilla::Plugin::Prereqs: 4.300014
    Dist::Zilla::Plugin::PruneCruft: 4.300014
    Dist::Zilla::Plugin::ReadmeFromPod: 0.16
    Dist::Zilla::Plugin::ReportVersions::Tiny: 1.03
    Dist::Zilla::Plugin::Test::CPAN::Changes: 0.005
    Dist::Zilla::Plugin::Test::Compile: 1.112820
    Dist::Zilla::Plugin::Test::Kwalitee: 2.03
    Dist::Zilla::Plugin::Test::MinimumVersion: 2.0.1
    Dist::Zilla::Plugin::Test::Perl::Critic: 2.112410
    Dist::Zilla::Plugin::TestRelease: 4.300014
    Dist::Zilla::Plugin::Twitter: 0.015
    Dist::Zilla::Plugin::UploadToCPAN: 4.300014
    Dist::Zilla::PluginBundle::Author::KENTNL: NA(undef)
    Dist::Zilla::PluginBundle::Author::KENTNL::Lite: 'NA(possibly not installed)'
    Dist::Zilla::Role::FileGatherer: 4.300014
    Dist::Zilla::Role::MintingProfile::ShareDir: 4.300014
    Dist::Zilla::Role::PluginBundle: 4.300014
    File::Find: 1.20
    File::Temp: 0.22
    File::pushd: 1.002
    FindBin: 1.51
    Git::Wrapper: 0.017
    IO::Socket::SSL: 1.64
    JSON: 2.53
    LWP::Protocol::https: 6.03
    Module::Build: 0.4
    Moose: 2.0403
    Moose::Autobox: 0.12
    MooseX::Has::Sugar: 0.05070420
    MooseX::Types: 0.31
    Net::SSLeay: 1.47
    Path::Class: 0.25
    Perl::PrereqScanner: 1.011
    Pod::Coverage::TrustPod: 0.100001
    Pod::Weaver::Plugin::Encoding: 0.01
    String::Formatter: 0.102082
    Test::CPAN::Meta: 0.18
    Test::DZil: 4.300014
    Test::EOL: 1.1
    Test::Fatal: 0.010
    Test::File::ShareDir: 0.3.1
    Test::More: 1.005000004
    Test::Output: 1.01
    Test::Perl::Critic: 1.02
    namespace::autoclean: 0.13
    perl: 'NA(skipped: perl)'
    strict: 1.06
    version: 0.97
    warnings: 1.13
  perl:
    original: v5.15.9
    qv: 1
    version:
      - 5
      - 15
      - 9
  perl-config:
    gccversion: 4.5.3
    myarchname: x86_64-linux
    osname: linux
  platform: linux
  uname: 'Linux 3.3.1-gentoo x86_64 GenuineIntel GNU/Linux'
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::KENTNL/Git::NextVersion'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::KENTNL/MetaConfig'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::KENTNL/GithubMeta'
      version: 0.28
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Author::KENTNL/MetaProvides::Package'
      version: 1.14000001
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_config: 1
          show_uname: 1
          uname:
            uname_args:
              - '-s'
              - '-o'
              - '-r'
              - '-m'
              - '-i'
            uname_call: uname
      name: '@Author::KENTNL/MetaData::BuiltWith'
      version: 0.03000000
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Author::KENTNL/Git::GatherDir'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::KENTNL/License'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::KENTNL/MetaJSON'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::KENTNL/MetaYAML'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::KENTNL/Manifest'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::KENTNL/MetaTests'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::KENTNL/PodCoverageTests'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::KENTNL/PodSyntaxTests'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Author::KENTNL/ReportVersions::Tiny'
      version: 1.03
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: '@Author::KENTNL/Test::Kwalitee'
      version: 2.03
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::KENTNL/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::KENTNL/Test::MinimumVersion'
      version: 2.0.1
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Author::KENTNL/Test::Compile'
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::KENTNL/Test::Perl::Critic'
      version: 2.112410
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::KENTNL/PruneCruft'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::KENTNL/ManifestSkip'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::KENTNL/PkgVersion'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Author::KENTNL/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::KENTNL/NextRelease'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::KENTNL/AutoPrereqs'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/Prereqs/BundleDevelNeeds'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: recommends
      name: '@Author::KENTNL/Prereqs/BundleDevelRecommends'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: suggests
      name: '@Author::KENTNL/Prereqs/BundleDevelSuggests'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::Author::KENTNL::MinimumPerl
      name: '@Author::KENTNL/Author::KENTNL::MinimumPerl'
      version: ~
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::KENTNL/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Author::KENTNL/ModuleBuild'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@Author::KENTNL/ReadmeFromPod'
      version: 0.16
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::KENTNL/Test::CPAN::Changes'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@Author::KENTNL/CheckExtraTests'
      version: 0.004
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::KENTNL/TestRelease'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::KENTNL/ConfirmRelease'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::KENTNL/Git::Check'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::KENTNL/Git::Tag/tag_master'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::KENTNL/Git::Commit'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@Author::KENTNL/Git::CommitBuild'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::KENTNL/Git::Tag/tag_release'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::KENTNL/UploadToCPAN'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@Author::KENTNL/Twitter'
      version: 0.015
    -
      class: Dist::Zilla::Plugin::ModuleShareDirs
      name: ModuleShareDirs
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: DevelopRequires
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300014
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300014
x_authority: cpan:KENTNL
