---
abstract: 'BeLike::KENTNL when you build your distributions.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102346, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-KENTNL
provides:
  Dist::Zilla::MintingProfile::Author::KENTNL:
    file: lib/Dist/Zilla/MintingProfile/Author/KENTNL.pm
    version: 0.01023311
  Dist::Zilla::Plugin::Author::KENTNL::DistINI:
    file: lib/Dist/Zilla/Plugin/Author/KENTNL/DistINI.pm
    version: 0.01023311
  Dist::Zilla::PluginBundle::KENTNL:
    file: lib/Dist/Zilla/PluginBundle/KENTNL.pm
    version: 0.01023311
requires:
  Carp: 0
  Class::Load: 0
  Dist::Zilla: 4.101612
  Dist::Zilla::File::FromCode: 0
  Dist::Zilla::Plugin::AutoPrereq: 0
  Dist::Zilla::Plugin::AutoVersion::Relative: 0.01035617
  Dist::Zilla::Plugin::CompileTests: 1.101800
  Dist::Zilla::Plugin::ConfirmRelease: 0
  Dist::Zilla::Plugin::CriticTests: 1.102280
  Dist::Zilla::Plugin::EOLTests: 0.02
  Dist::Zilla::Plugin::ExtraTests: 0
  Dist::Zilla::Plugin::FakeRelease: 0
  Dist::Zilla::Plugin::GatherDir: 0
  Dist::Zilla::Plugin::Git::Check: 1.102040
  Dist::Zilla::Plugin::Git::CommitBuild: 1.102040
  Dist::Zilla::Plugin::Git::Tag: 1.102040
  Dist::Zilla::Plugin::GithubMeta: 0.08
  Dist::Zilla::Plugin::KwaliteeTests: 1.101420
  Dist::Zilla::Plugin::License: 0
  Dist::Zilla::Plugin::Manifest: 0
  Dist::Zilla::Plugin::ManifestSkip: 0
  Dist::Zilla::Plugin::MetaConfig: 0
  Dist::Zilla::Plugin::MetaData::BuiltWith: 0.01014716
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaProvides: 1.12044518
  Dist::Zilla::Plugin::MetaProvides::Package: 1.11044404
  Dist::Zilla::Plugin::MetaTests: 0
  Dist::Zilla::Plugin::MetaYAML: 0
  Dist::Zilla::Plugin::ModuleBuild: 0
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 3.093321
  Dist::Zilla::Plugin::PortabilityTests: 1.101420
  Dist::Zilla::Plugin::PruneCruft: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0.12
  Dist::Zilla::Plugin::ReportVersions::Tiny: 1.01
  Dist::Zilla::Plugin::TestRelease: 0
  Dist::Zilla::Plugin::Twitter: 0.007
  Dist::Zilla::Plugin::UploadToCPAN: 0
  Dist::Zilla::Role::FileGatherer: 0
  Dist::Zilla::Role::MintingProfile::ShareDir: 0
  Dist::Zilla::Role::PluginBundle: 0
  IO::Socket::SSL: 0
  Moose: 1.01
  Moose::Autobox: 0
  MooseX::Has::Sugar: 0.05044
  MooseX::Types: 0.21
  Net::SSLeay: 1.36
  Pod::Coverage::TrustPod: 0
  String::Formatter: 0
  Test::CPAN::Meta: 0
  Test::EOL: 0.9
  namespace::autoclean: 0.09
resources:
  homepage: http://github.com/kentfredric/dist-zilla-pluginbundle-kentnl/tree
  repository: git://github.com/kentfredric/dist-zilla-pluginbundle-kentnl.git
version: 0.01023311
x_BuiltWith:
  modules:
    Carp: 1.17
    Class::Load: 0.06
    Dist::Zilla: 4.102346
    Dist::Zilla::File::FromCode: 4.102346
    Dist::Zilla::Plugin::AutoPrereq: 4.102346
    Dist::Zilla::Plugin::AutoVersion::Relative: 0.01037118
    Dist::Zilla::Plugin::Bootstrap::lib: 0.01000003
    Dist::Zilla::Plugin::CompileTests: 1.103030
    Dist::Zilla::Plugin::ConfirmRelease: 4.102346
    Dist::Zilla::Plugin::CriticTests: 1.102280
    Dist::Zilla::Plugin::EOLTests: 0.02
    Dist::Zilla::Plugin::ExtraTests: 4.102346
    Dist::Zilla::Plugin::FakeRelease: 4.102346
    Dist::Zilla::Plugin::GatherDir: 4.102346
    Dist::Zilla::Plugin::Git::Check: 1.102810
    Dist::Zilla::Plugin::Git::CommitBuild: 1.102810
    Dist::Zilla::Plugin::Git::Tag: 1.102810
    Dist::Zilla::Plugin::GithubMeta: 0.10
    Dist::Zilla::Plugin::KwaliteeTests: 1.101420
    Dist::Zilla::Plugin::License: 4.102346
    Dist::Zilla::Plugin::Manifest: 4.102346
    Dist::Zilla::Plugin::ManifestSkip: 4.102346
    Dist::Zilla::Plugin::MetaConfig: 4.102346
    Dist::Zilla::Plugin::MetaData::BuiltWith: 0.01018204
    Dist::Zilla::Plugin::MetaJSON: 4.102346
    Dist::Zilla::Plugin::MetaProvides: 1.12044806
    Dist::Zilla::Plugin::MetaProvides::Package: 1.12044908
    Dist::Zilla::Plugin::MetaTests: 4.102346
    Dist::Zilla::Plugin::MetaYAML: 4.102346
    Dist::Zilla::Plugin::ModuleBuild: 4.102346
    Dist::Zilla::Plugin::PkgVersion: 4.102346
    Dist::Zilla::Plugin::PodCoverageTests: 4.102346
    Dist::Zilla::Plugin::PodSyntaxTests: 4.102346
    Dist::Zilla::Plugin::PodWeaver: 3.101641
    Dist::Zilla::Plugin::PortabilityTests: 1.101420
    Dist::Zilla::Plugin::PruneCruft: 4.102346
    Dist::Zilla::Plugin::ReadmeFromPod: 0.14
    Dist::Zilla::Plugin::ReportVersions::Tiny: 1.02
    Dist::Zilla::Plugin::TestRelease: 4.102346
    Dist::Zilla::Plugin::Twitter: 0.009
    Dist::Zilla::Plugin::UploadToCPAN: 4.102346
    Dist::Zilla::PluginBundle::KENTNL: NA(undef)
    Dist::Zilla::PluginBundle::KENTNL::Lite: 0.01000002
    Dist::Zilla::Role::FileGatherer: 4.102346
    Dist::Zilla::Role::MintingProfile::ShareDir: 4.102346
    Dist::Zilla::Role::PluginBundle: 4.102346
    File::Temp: 0.22
    IO::Socket::SSL: 1.35
    Module::Build: 0.3607
    Moose: 1.21
    Moose::Autobox: 0.11
    MooseX::Has::Sugar: 0.05055616
    MooseX::Types: 0.24
    Net::SSLeay: 1.36
    Pod::Coverage::TrustPod: 0.092832
    String::Formatter: 0.102082
    Test::CPAN::Meta: 0.17
    Test::EOL: 0.9
    Test::More: 0.96
    namespace::autoclean: 0.11
  perl:
    original: v5.12.2
    qv: 1
    version:
      - 5
      - 12
      - 2
  platform: linux
  uname: 'Linux 2.6.36-gentoo-r3 x86_64 GenuineIntel GNU/Linux'
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::AutoVersion::Relative
      config:
        Dist::Zilla::Plugin::AutoVersion::Relative:
          format: "{{ sprintf('%d.%02d%04d%02d', $major, $minor, days, hours) }}"
          major: 0
          minor: 1
          relative_to:
            day: 16
            hour: 20
            minute: 0
            month: 5
            second: 0
            time_zone: Pacific/Auckland
            year: 2010
      name: '@KENTNL/AutoVersion::Relative'
      version: 0.01037118
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@KENTNL/GatherDir'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@KENTNL/MetaConfig'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@KENTNL/PruneCruft'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@KENTNL/GithubMeta'
      version: 0.10
    -
      class: Dist::Zilla::Plugin::License
      name: '@KENTNL/License'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@KENTNL/PkgVersion'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@KENTNL/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@KENTNL/MetaProvides::Package'
      version: 1.12044908
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@KENTNL/MetaJSON'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@KENTNL/MetaYAML'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@KENTNL/ModuleBuild'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@KENTNL/ReadmeFromPod'
      version: 0.14
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@KENTNL/ManifestSkip'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@KENTNL/Manifest'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@KENTNL/AutoPrereqs'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@KENTNL/Prereqs/BundleDevelNeeds'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: recommends
      name: '@KENTNL/Prereqs/BundleDevelRecommends'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: suggests
      name: '@KENTNL/Prereqs/BundleDevelSuggests'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_uname: 1
          uname:
            uname_args:
              - '-s'
              - '-o'
              - '-r'
              - '-m'
              - '-i'
            uname_call: uname
      name: '@KENTNL/MetaData::BuiltWith'
      version: 0.01018204
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@KENTNL/CompileTests'
      version: 1.103030
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: '@KENTNL/CriticTests'
      version: 1.102280
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@KENTNL/MetaTests'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@KENTNL/PodCoverageTests'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@KENTNL/PodSyntaxTests'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@KENTNL/ReportVersions::Tiny'
      version: 1.02
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@KENTNL/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@KENTNL/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@KENTNL/ExtraTests'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@KENTNL/TestRelease'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@KENTNL/ConfirmRelease'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@KENTNL/Git::Check'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@KENTNL/NextRelease'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@KENTNL/Git::Tag/tag_master'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@KENTNL/Git::Commit'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@KENTNL/Git::CommitBuild'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@KENTNL/Git::Tag/tag_release'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@KENTNL/UploadToCPAN'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@KENTNL/Twitter'
      version: 0.009
    -
      class: Dist::Zilla::Plugin::ModuleShareDirs
      name: ModuleShareDirs
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: DevelopRequires
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.102346
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.102346
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.102346
